lib/components/quick_links_bar.dart, lib/screens/settings/quick_links.dart
Hi,
- Duplicate links are not allowed.
- Empty links are not allowed.
- Web URLs are opened using ChromeSafariBrowser (other schemes are launched with url_launcher)
=> update quick link creation and launch

lib/components/chat_history/message.dart, lib/components/chat_history/twitch/message.dart, lib/components/font_size_picker.dart, lib/components/tts_options_panel.dart, lib/models/chat_history.dart, lib/models/message.dart, lib/models/style.dart, lib/models/tts.dart, lib/models/twitch/user.dart
This will be useful for adding additional events types.
=> chore: refactor out user logic to separate model

lib/components/chat_history/twitch/message.dart, lib/components/pinnable/scroll_view.dart
Temporarily disable link previews for prod release. I'll revert this change after today :)
=> chore: disable link previews

lib/components/chat_history/twitch/message.dart, lib/models/twitch/emote.dart
=> fix: animate twitch emotes

lib/components/channel_panel.dart
=> fix: increase size of drag target

.github/workflows/flutter-test.yml, lib/components/chat_history/message.dart, lib/components/chat_history/twitch/message.dart, lib/components/chat_history/twitch/raid_event.dart, lib/components/font_size_picker.dart, lib/models/chat_history.dart, lib/models/message.dart, lib/models/twitch/event.dart, lib/models/twitch/message.dart, lib/models/twitch/third_party_emote.dart, test/models/twitch/message_test.dart
This should speed up rendering the chat history a bit by reducing the number of widgets.
=> chore: refactor message parsing

lib/models/twitch/third_party_emote.dart
=> feat: add 7tv emote support

agent/package-lock.json, agent/package.json, agent/src/index.ts
This allows us to more robustly detect when an agent is disconnected. Closes #15
=> feat: ask twitch for locking status

agent/package-lock.json, agent/package.json, agent/src/index.ts
=> Revert "feat: ask twitch for locking status"

lib/components/chat_history/message.dart, lib/main.dart, pubspec.lock, pubspec.yaml
Adds a feature flag for the new inline events, for profile or release modes.
Closes #114
=> feat: add feature flag for inline events

functions/src/auth.ts, functions/src/eventsub.ts
This allows channel point redemption events to be stored in the database.
=> feat: store channel point redemptions

lib/components/chat_history/twitch/message.dart
`NetworkImageWithRetry` doesn't support animated gifs apparently.
=> fix: use Image.network for emotes

lib/screens/settings/quick_links.dart
This makes adding quick links a bit less strange, and matches the behaviour for audio sources.
=> feat: add quick link on edit completion

lib/components/chat_history/stream_state_event.dart, lib/components/chat_history/twitch/cheer_event.dart, lib/components/chat_history/twitch/follow_event.dart, lib/components/chat_history/twitch/hype_train_event.dart, lib/components/chat_history/twitch/message.dart, lib/components/chat_history/twitch/message_link_preview.dart, lib/components/chat_history/twitch/raid_event.dart, lib/components/chat_history/twitch/subscription_event.dart, lib/components/chat_history/twitch/subscription_gift_event.dart, lib/components/chat_history/twitch/subscription_message_event.dart, lib/components/chat_panel.dart, lib/components/font_size_picker.dart, lib/components/style_model_theme.dart
This change simplifies and makes the typography in the chat history a bit more consistent.
=> chore: clean up chat history font sizes

lib/components/chat_history/twitch/poll_event.dart, lib/screens/settings/events.dart
Makes the page a little more lively.
=> feat: add event previews

lib/components/chat_history/message.dart, lib/components/chat_panel.dart, lib/main.dart, lib/models/messages/twitch/eventsub_configuration.dart, lib/screens/settings/events/subscription.dart
=> feat: add configuration for twitch sub events

lib/components/chat_history/message.dart, lib/components/chat_panel.dart, lib/main.dart, lib/models/messages/twitch/eventsub_configuration.dart, lib/models/messages/twitch/prediction_event.dart, lib/screens/settings/events.dart, lib/screens/settings/events/prediction.dart, test/components/chat_history/twitch/prediction_event_test.dart
=> feat: add prediction configuration

android/.idea/gradle.xml, android/.idea/modules.xml, android/.idea/modules/android.iml, lib/screens/home.dart
=> fix: shrink notification panel when keyboard showing

lib/components/chat_history/message.dart
=> style: add leading icons to long press options

lib/components/chat_history/decorated_event.dart, lib/components/chat_history/twitch/message.dart, lib/screens/settings/backup.dart, lib/screens/settings/chat_history.dart, lib/screens/settings/events/channel_point.dart, lib/screens/settings/events/cheer.dart, lib/screens/settings/events/follow.dart, lib/screens/settings/events/hypetrain.dart, lib/screens/settings/events/poll.dart, lib/screens/settings/events/prediction.dart, lib/screens/settings/events/raid.dart, lib/screens/settings/events/subscription.dart, lib/screens/settings/settings.dart, lib/screens/settings/tts.dart
https://flutter.dev/docs/release/breaking-changes/theme-data-accent-properties#accentcolor
=> chore: migrate accentColor to secondary

lib/components/chat_history/message.dart, lib/models/messages/tts_audio_handler.dart, lib/models/messages/twitch/user.dart, lib/models/tts.dart
ig we can probably have a settings page for viewing the blacklist. A form for adding a name to the blacklist and swiping list item to remove from blacklist
=> feat: option to blacklist a user in tts

lib/screens/settings/events.dart
=> feat: add quick toggle switches for twitch events

lib/components/chat_panel.dart
=> feat: make the bottom button look nicer

lib/components/chat_panel.dart, lib/main.dart, lib/models/messages/twitch/message.dart, lib/models/messages/twitch/message_configuration.dart, lib/screens/settings/chat_history.dart, test/models/messages/twitch/message_configuration_test.dart
=> feat: pin mod/vip messages

android/app/build.gradle
I think this should fix the build.
=> fix: increase android sdk version

agent/src/adapters/firebase.ts, agent/src/agents/twitch.ts
=> feat: publish host events from agent

functions/src/emotes.ts, functions/src/index.ts
=> fix: retrieve twitch emotes using helix api

agent/src/adapters/firebase.ts, agent/src/agents/twitch.ts, agent/src/index.ts
Closes #291 
This should also allow the agent to receive host events.
=> feat: update agent to use the user's account when available

ios/Podfile, ios/Podfile.lock
Updated the pod from 8.3.0 to 8.11.0
=> fix: update ios podfile

functions/src/auth.ts
This log pollutes the firebase logs for not much benefit.
=> chore: remove unnecessary error log

lib/components/drawer/end_drawer.dart, lib/components/drawer/sliver_title.dart, lib/screens/home.dart
=> feat: list viewers in a drawer

agent/src/agents/twitch.ts
Turns out it's pulling the wrong id right now this is the user's id oops.
=> fix: remove channelId

agent/src/adapters/firebase.ts, agent/src/agents/twitch.ts
=> feat: add channel ids to host events

lib/components/header_bar.dart, lib/models/adapters/messages.dart
=> feat: add stream uptime

lib/components/drawer/sidebar.dart
=> fix: close log out modal when confirming

lib/models/tts.dart
=> fix: support system message vocalization

lib/components/header_bar.dart
=> fix: title overflow behavior

lib/models/tts.dart
=> fix: use platform dependent default for tts speed

lib/components/activity_feed_panel.dart, lib/screens/home.dart
=> fix: reconfigure inappwebview for better performance

lib/components/channel_search_bottom_sheet.dart
Updates search sheet headline size, alignment and wording to follow
proposed style.
=> fix: update search sheet headline

lib/screens/settings/settings.dart
Used the AboutTile as a replacement of the current Tile, let me know if I should the previous one instead...
Also moved the easter egg into the dialog with some phrase which might not be good enough lol.
=> feat: add license page shortcut

lib/main.dart
Updates dark theme to more closely match the colors for the new style, this does not cover every single element.
=> feat: update dark theme

lib/models/messages.dart, lib/models/tts.dart
=> fix: disable tts when channel changes

lib/components/channel_search_bottom_sheet.dart, lib/components/channel_search_results.dart, lib/main.dart, lib/theme_colors.dart
Updates the following:
- Update search bar result icons now use blue when online, transparent when offline.
- Update headline color for dark theme.
- Update text field fill color.
- Disabled text field border color fill.
=> chore: update search bar style

lib/models/adapters/messages.dart, lib/models/messages/twitch/event.dart
https://console.firebase.google.com/u/0/project/rtchat-47692/crashlytics/app/android:com.rtirl.chat/issues/c1cd7c8c630f17374163d6858fec006b?time=last-seven-days&sessionEventKey=6277D7C501680001582379A196065D8A_1673847815802295894
=> fix: anonymous cheer

lib/screens/home.dart
=> fix: unnecessary null operator

lib/components/chat_panel.dart, lib/components/pinnable/scroll_view.dart, lib/screens/home.dart
This is a pretty dramatic performance improvement. xqc's channel renders with very little lagging after this change. :)
Closes #292
=> fix: improve unpinned messages rendering

agent/src/agents/twitch.ts
=> chore: migrate author to its own field

android/app/src/main/AndroidManifest.xml
https://console.firebase.google.com/u/0/project/rtchat-47692/crashlytics/app/android:com.rtirl.chat/issues/382f0c986e4debffc37509d247f1d90b?time=last-seven-days&sessionEventKey=62804840034500016A70D3F3FF4126AA_1676198056007602810
=> fix: remove nonexistent receiver

lib/models/messages/twitch/prediction_event.dart
https://console.firebase.google.com/u/0/project/rtchat-47692/crashlytics/app/ios:com.rtirl.chat/issues/6b00eeee0cae51ab578d73aa3f363742?time=last-seven-days&sessionEventKey=5a8fb55e210c488c93dede028bf54013_1678140609325643164
=> fix: prediction event parsing

lib/components/channel_search_results.dart, lib/components/chat_history/twitch/badge.dart, lib/components/chat_history/twitch/cheer_event.dart, lib/components/chat_history/twitch/follow_event.dart, lib/components/chat_history/twitch/host_event.dart, lib/components/chat_history/twitch/message.dart, lib/components/chat_history/twitch/message_link_preview.dart, lib/components/chat_history/twitch/raid_event.dart, lib/components/chat_history/twitch/raiding_event.dart, lib/components/drawer/sidebar.dart, lib/components/emote_picker.dart, lib/components/image/resilient_network_image.dart, lib/models/channels.dart, lib/models/messages/twitch/user.dart, lib/screens/settings/twitch/badges.dart, pubspec.lock, pubspec.yaml, test/components/chat_history/twitch/cheer_event_test.dart
=> feat: implement resilient network image

lib/screens/settings/settings.dart
=> fix: capitalization

lib/components/channel_search_bottom_sheet.dart, lib/components/channel_search_results.dart, lib/components/chat_history/twitch/poll_indicator.dart, lib/components/chat_history/twitch/raiding_event.dart
This migrates all of the cases that were using the color constant class to get a color instead of the active theme.
=> chore: always grab colors from theme

lib/models/messages/twitch/prediction_event.dart
=> fix: improve prediction event parsing

lib/components/drawer/sidebar.dart, lib/components/image/resilient_network_image.dart
Fix for https://github.com/flutter/flutter/issues/105315
Seems that our network image is causing problems?
Fixes #477
=> fix: disable pending image cache

lib/components/drawer/sidebar.dart
closes #473 
Tapping the banner when the user isn't signed in brings them to the onboarding screen.
=> feat: add shortcut to user's channel

agent/src/adapters/firebase.ts, agent/src/agents/twitch.ts, agent/src/index.ts
This wires up the agent to accept message requests so we can send messages faster.
=> feat: send messages via connected agent

lib/screens/settings/activity_feed.dart
=> feat: make preview expandable

lib/components/chat_history/twitch/message_link_preview.dart
=> feat: reenable link previews

lib/models/audio.dart
Allows silence to play while other music is playing.
Fixes #508
=> fix: enable duckAudio

agent/src/agents/twitch.ts
If messages are sent on the same client, the onMessage() callback doesn't trigger. The easiest fix is to send the message on a separate client.
=> fix: use separate client for sending messages

functions/package-lock.json, functions/package.json, functions/src/index.ts, functions/src/twitch.ts
=> feat: wire up functions to send to firebase actions

lib/components/emote_picker.dart, lib/components/message_input.dart, lib/main.dart, lib/theme_colors.dart
closes #332 
- add send button to text field
- change text field color to pull from theme
- add Material ripples to Icon Buttons (text field icons, emotes, emote menu buttons)
- align emote menu buttons to bottom
=> feat: update home screen

lib/components/drawer/sliver_search_bar.dart
Changes search box color to pull from the theme
=> style: change `endDrawer` search box color

lib/components/chat_history/message.dart, lib/models/layout.dart, lib/screens/home.dart, lib/screens/settings/settings.dart
Closes #498.
Actually not 100% sure this is the right choice, what do you think?
=> feat: force interaction lock

lib/components/drawer/end_drawer.dart
I forgot to add extra padding to the broadcaster list in #516
=> fix: add padding to broadcaster list

lib/components/drawer/sidebar.dart
Currently the usable height of the drawer header can vary between phones
=> fix: add `SafeArea` to drawer header

lib/components/chat_history/twitch/message.dart, lib/models/adapters/messages.dart, lib/models/messages/twitch/message.dart, lib/models/messages/twitch/reply.dart
closes #305 
Ellipsizing is weird in flutter as it cuts off whole words. It is mainly a problem when using large font sizes.
flutter/flutter#18761
=> feat: render replies

lib/screens/settings/chat_history.dart
Someone requested the ability to have 18px font.
=> feat: increase number of divisions on font size

.github/workflows/firebase.yml, database.rules.json, lib/components/chat_panel.dart, lib/components/connection_status.dart, pubspec.lock, pubspec.yaml
=> feat: add connection status bar when disconnected

lib/main.dart
https://github.com/muxable/rtchat/blob/4f9eabac84bb31e6c4cbb767f59d62361dcc598c/lib/main.dart#L176-L190
https://github.com/muxable/rtchat/blob/4f9eabac84bb31e6c4cbb767f59d62361dcc598c/lib/main.dart#L217-L231
=> chore: remove duplicate provider

lib/components/message_input.dart
=> feat: use random twitch emote for emote picker icon

functions/src/index.ts, functions/src/tts.ts
* add `getVoices` method
* add voice name, speech rate, and pitch parameters
=> feat: update cloud tts endpoint

lib/components/chat_history/twitch/subscription_event.dart, lib/models/adapters/messages.dart, lib/models/messages/twitch/subscription_message_event.dart
=> feat: render resubscription message

lib/components/drawer/quicklinks_listview.dart, pubspec.lock, pubspec.yaml
=> fix: fix custom tabs opening duplicate

lib/components/drawer/quicklinks_listview.dart
=> feat: ellipsize sidebar quicklink url

lib/models/tts.dart
=> fix: call notify listeners after build

lib/components/drawer/quicklinks_listview.dart
suggestion from [eric](https://discord.com/channels/823598483255722056/846232108930564126/1005117766094827550)
=> feat: copy url from quicklink

lib/models/tts.dart, lib/models/tts/bytes_audio_source.dart, lib/screens/settings/tts.dart, lib/screens/settings/tts/voices.dart, pubspec.lock, pubspec.yaml
=> feat: add cloud tts

lib/models/tts.dart, lib/screens/settings/tts.dart
=> feat: add mute username prelude option

lib/models/tts.dart, lib/screens/settings/tts.dart
Reverts muxable/rtchat#601
closes #602
=> Revert "feat: add mute username prelude option"

functions/src/subscriptions.ts
Now that we have some GCP credits we don't need to worry about our bill so much.
=> chore: update subscription expiration to one week

firestore.rules
=> feat: add firestore rule for reading streamlabs collection

lib/components/stream_preview.dart
=> fix: switch stream preview when channel changes

lib/components/stream_preview.dart
=> fix: disable overlay when video is not playing, add loading overlay

lib/components/stream_preview.dart, lib/models/stream_preview.dart
Fixes [stream_preview] show a snackbar if the user has left preview open for five minutes #605
=> feat: add battery prompt

agent/src/agents/twitch.ts
=> feat: add annotations to agent

firestore.rules, functions/src/eventsub.ts, lib/components/stream_preview.dart
This will be used to speed up searches
=> feat: add some logging for online/offline status and metadata

firestore.rules, functions/src/chat-status.ts, functions/src/index.ts
We'll route chatter status through this endpoint which will be much faster.
=> feat: add periodic polling of chatters list

functions/src/chat-status.ts, functions/src/twitch.ts
This will be useful for analytics in the future.
=> feat: add channelId to chat status

lib/components/header_bar.dart
=> feat: switch header bar behavior

lib/components/drawer/sidebar.dart
This is probably a bit clearer on what it does
=> chore: rename lock layout to lock interaction

functions/.gitignore, functions/package-lock.json, functions/package.json, functions/src/alchemy_webhook.ts, functions/src/auth.ts, functions/src/chat-status.ts, functions/src/emotes.ts, functions/src/eventsub.ts, functions/src/index.ts, functions/src/search.ts, functions/src/tts.ts, functions/src/twitch.ts
=> feat: new emotes api + upgrade packages

lib/components/autocomplete.dart, lib/components/message_input.dart, lib/models/chat_state.dart
=> feat: add emote autocomplete

agent/src/agents/twitch.ts
For some reason even if the agent is connected, Twitch doesn't always send messages. Wait for the first message before claiming a handover.
=> fix: wait for first message before claiming

lib/models/messages.dart
=> fix: reorder messages if timestamp ordering incorrect

lib/components/channel_search_results.dart
=> feat: increase search space

lib/models/chat_state.dart
This is causing some lag on larger channels
=> fix: reduce viewer search result size

functions/src/alchemy_webhook.ts
Can't write to db after invoking the function, the firebase rules are there.
Logging to see what failed.
=> chore: error-logging for address setter

functions/src/alchemy_webhook.ts, lib/models/adapters/donations.dart, lib/screens/settings/donations.dart
eth address not case sensitive, and the webhook response `toAddress` is all lowercase
=> fix: lowercase for eth public addr

lib/components/chat_panel.dart
=> fix: scroll to bottom when changing channels

lib/components/chat_history/decorated_event.dart
=> fix: improve decoration alignment

lib/components/header_bar.dart
Sometimes the word "uptime" is too long
=> fix: uptime -> up

lib/main.dart, lib/models/layout.dart
This should fix the navigation bar color being white in dark mode. Although I can't reproduce that issue...
=> fix: try a different approach to setting the nav bar color

lib/main.dart, lib/models/layout.dart
It looks nicer when it works. It's not easy to detect old versions to fall back to correctly assigning colors though. I guess old versions and we'll have to recommend people upgrade phones if anyone asks :(
=> fix: revert back to using edge to edge

functions/src/index.ts, lib/components/chat_history/message.dart, lib/models/adapters/actions.dart
Turns out it's possible to ban without providing a reason, we should do that.
=> fix: remove ban reason

lib/models/messages/twitch/message.dart
=> fix: correct emote end index

lib/screens/settings/activity_feed.dart
=> feat: add button to clear cookies to settings page

lib/components/emote_picker.dart
=> feat: prioritize channel emotes after global emotes

lib/components/autocomplete.dart
=> fix: add prefix search for commands

functions/src/chat-status.ts, functions/src/index.ts
=> feat: add viewer count batching

functions/src/chat-status.ts, functions/src/index.ts, lib/components/drawer/end_drawer.dart, lib/models/adapters/chat_state.dart
=> fix: migrate to pull-based chatter api

lib/screens/home.dart
=> fix: always show message input field

agent/src/agents/twitch.ts, functions/src/index.ts
=> Revert "feat: migrate actions to individual channel collections"

lib/components/emote_picker.dart
https://console.firebase.google.com/u/0/project/rtchat-47692/crashlytics/app/android:com.rtirl.chat/issues/b2760422bafbd422e45820c3fe6f2b29?time=last-seven-days&sessionEventKey=6389F46F0151000177CD0624CCA3CCA0_1750978308151244677
```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Null check operator used on a null value. Error thrown null.
at State.context(framework.dart:942)
at TickerProviderStateMixin._updateTickerModeNotifier(ticker_provider.dart:327)
at TickerProviderStateMixin.createTicker(ticker_provider.dart:291)
at new AnimationController.unbounded(animation_controller.dart:283)
at .new TabController(tab_controller.dart:110)
at _EmotePickerWidgetState.initState.<fn>(emote_picker.dart:90)
```
=> fix: race condition in emote picker

lib/components/chat_history/decorated_event.dart, lib/components/chat_history/twitch/subscription_event.dart, lib/models/adapters/messages.dart, lib/models/messages/twitch/subscription_message_event.dart
=> feat: improve subscription event

functions/src/chat-status.ts, lib/models/adapters/chat_state.dart
I believe this is why the function is 404'ing
=> fix: pass proper token to getViewerList

lib/components/channel_search_results.dart
=> feat: add language hint in search results

functions/src/subscriptions.ts
=> feat: send welcome message

functions/src/chat-status.ts
If login is missing then outbound actions will fail. In case it gets deleted for some unknown reason, we will automatically repopulate it here.
=> fix: also periodically update login

lib/components/chat_history/decorated_event.dart, lib/components/chat_history/twitch/follow_event.dart, lib/components/chat_panel.dart, lib/models/messages/twitch/event.dart, lib/screens/settings/events.dart
=> feat: batch adjacent follower messages

lib/components/chat_panel.dart
=> fix: hide duplicate subscriptions

lib/models/messages/auxiliary/streamlabs.dart
Also fixes https://console.firebase.google.com/u/1/project/rtchat-47692/crashlytics/app/android:com.rtirl.chat/issues/f54c3037b7b54ceb6cdd596943c239b9
=> fix: remove unused field

lib/models/messages/twitch/message.dart
Fixes https://console.firebase.google.com/u/0/project/rtchat-47692/crashlytics/app/ios:com.rtirl.chat/issues/cda2cdd5dddb40d906adc9a7d33bf4ff?time=last-seven-days&sessionEventKey=184bd705b6d24f66b8eda70ff853e745_1768856590687815472
=> fix: incorrect emote tokenization

functions/src/eventsub.ts
=> fix: shoutout request body incomplete

lib/components/channel_search_results.dart, lib/components/chat_history/decorated_event.dart, lib/components/drawer/sidebar.dart, lib/components/emote_picker.dart, lib/components/header_bar.dart, lib/components/image/cross_fade_image.dart, lib/components/image/placeholder_image.dart, lib/components/image/resilient_network_image.dart, lib/models/channels.dart, lib/models/messages/twitch/emote.dart, lib/screens/settings/twitch/badges.dart
This change reads from the cache and immediately loads images if they are available. Meanwhile, a network request occurs and the new image is faded to if a new image is received.
=> feat: make image loading faster

lib/components/chat_panel.dart
=> fix: add missing setState() call

lib/screens/settings/twitch/badges.dart
https://github.com/muxable/rtchat/pull/915 this was intentional so this reverts that
=> fix: revert pr 915

lib/components/channel_search_results.dart
=> feat: support searching and rendering logins

functions/src/subscriptions.ts
https://console.cloud.google.com/errors/detail/COzWnf3Vp4uJKg?project=rtchat-47692
=> fix: no document to update errors

functions/src/index.ts
https://console.cloud.google.com/errors/detail/CK7I7JOc1eWh7QE;time=P7D?project=rtchat-47692
=> fix: handle 404 channel

functions/src/auth.ts
https://console.cloud.google.com/errors/detail/CIqT6qTR_aTQcA?project=rtchat-47692
=> fix: coerce undefined email to null

lib/components/message_input.dart
This prevents a rerender of the component.
=> fix: remove unnecessary setState() call

lib/screens/settings/settings.dart
My idea to move the button up as it is more of an app setting than a system setting, should also help people find it.
=> fix: button visibility

lib/components/chat_history/twitch/cheer_event.dart
Changes the logic to be clearer for cheering.
=> fix: cheer description

lib/screens/settings/settings.dart
Reverse ! for subtitles as best practice, removes the ! that I added in #883
=> fix: remove exclamation mark

lib/models/tts.dart, lib/screens/settings/tts.dart
This was requested in the discord so it will have some use.
=> feat: tts mute viewer names

ios/Flutter/Debug.xcconfig, ios/Flutter/Release.xcconfig
Resolves the following warning
=> fix: cocoapods base configuration

functions/src/index.ts, functions/src/twitch.ts
Need to test this carefully. In particular, our auth tokens don't have the right scope so it might not work well for a while.
=> fix: migrate to new ban api

functions/src/index.ts
=> fix: missing imports

pubspec.lock
=> fix: dart sdk

lib/screens/home.dart
In rare occasions this seems to cause a crash.
https://console.firebase.google.com/u/0/project/rtchat-47692/crashlytics/app/android:com.rtirl.chat/issues/bca7787299e07f2f731979eabb0dd60a
=> fix: invalid clamping range

lib/screens/home.dart
The Twitch API doesn't correctly return the viewers if the user isn't signed in.
=> fix: disable viewer list in guest mode

lib/firebase_options.dart
This is just testing to see really if github-actions bot works
=> fix: indent

pubspec.lock, pubspec.yaml
Tested on stream 2023-07-16 with my chat
=> fix: minor upgrades

lib/components/channel_search_results.dart
=> fix: long names not being displayed

lib/components/channel_search_results.dart
This fixes for #1076 the proper dart formatting
=> fix: dart style for 1076

lib/tts_plugin.dart
I was trying to test this and I was able to get it to work with this
=> fix: method for queue

lib/components/emote_picker.dart
This fixes the deprecation warnings.
=> fix: popscope deprecation

lib/screens/home.dart, lib/tts_isolate.dart
=> feat: create an empty isolate

lib/components/chat_history/decorated_event.dart
=> fix: sub message not spanning full width

android/build.gradle
https://mvnrepository.com/artifact/com.android.tools.build/gradle?repo=google
=> fix: agp compatible gradle

lib/models/tts.dart
This should resolve #1153 though it needs to be tested.
=> fix: use new tts in debug mode

lib/main.dart, lib/tts_isolate.dart
This should take care of #1151 though should be reviewed and tested.
=> fix: read collection messages for tts channel

lib/components/drawer/sidebar.dart, lib/screens/home.dart, lib/themes.dart
@kevmo314 Is this what you wanted? If it is then I'll throw up another commit on this branch to remove the code from the other PR I added
=> fix: better icon implementation

lib/screens/home.dart
This should take care of #1154 please double check it on your android simulator @jlw4049 when you have a chance.
=> fix: update tts button

lib/main.dart, pubspec.lock, pubspec.yaml
This removes the shared preferences in favor of streaming shared preferences which closes #1165
=> fix: remove shared_preferences

lib/components/disco.dart
This should fix #794 and make it consistent that everything flashes.
=> fix: disco mode not working

lib/components/channel_search_bottom_sheet.dart, lib/components/drawer/sidebar.dart
This adds a raid button on the sidebar to further use and help people find the raid button.
=> fix: add raid visibility

lib/main.dart, lib/screens/home.dart, lib/tts_isolate.dart, pubspec.lock, pubspec.yaml
I believe this will require just a few minor changes to support ios
=> fix: tts notifications

agent/internal/handler/twitch.go
https://discord.com/channels/823598483255722056/846232108930564126/1207810133636288594
=> fix: update access token before attempting a reconnect

android/app/build.gradle, android/build.gradle, android/settings.gradle, pubspec.lock
See https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply
=> chore: migrate flutter gradle plugin

lib/screens/settings/settings.dart
Channel name changed, this fixes the link
=> fix: update channel link

lib/main.dart, pubspec.lock, pubspec.yaml
Adds more explicit audio annotations so maybe it will behave better with Spotify and other applications.
=> chore: bump audioplayers version

ios/Podfile.lock, lib/components/scanner_settings.dart, pubspec.lock, pubspec.yaml
This upgrades the scanner to match the changes that got done in rtirl
=> chore: upgrade scanner

android/app/src/main/kotlin/com/rtirl/chat/MainActivity.kt, android/app/src/main/kotlin/com/rtirl/chat/NotificationService.kt
This should hopefully help fix the app crashing when service permissions not granted
=> fix: app crashing if permissions not granted

ios/Runner.xcodeproj/project.pbxproj, ios/Runner/Info.plist
This follows up on #1261 by forcing the build to use iOS 13 when building.
=> fix: deployment target

lib/tts_isolate.dart, lib/tts_plugin.dart
This adjusts the speech rate to match the old engine and makes sure the last message is not repeated
=> fix: last message and speech rate

lib/l10n/app_bn.arb, lib/l10n/app_de.arb, lib/l10n/app_es.arb, lib/l10n/app_fr.arb, lib/l10n/app_ja.arb, lib/l10n/app_nl.arb, lib/l10n/app_pt.arb, lib/l10n/app_zh.arb, lib/l10n/app_zh_Hant.arb
Adds some more translations
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/muxable/rtchat?shareId=296dc48f-2642-43fb-b879-38254b940eac).
=> feat: add translations for event configuration titles and subtitles

lib/l10n/app_bn.arb, lib/l10n/app_de.arb, lib/l10n/app_es.arb, lib/l10n/app_fr.arb, lib/l10n/app_ja.arb, lib/l10n/app_nl.arb, lib/l10n/app_pt.arb, lib/l10n/app_zh.arb, lib/l10n/app_zh_Hant.arb
Add translations for various event messages in multiple language files.
* **lib/l10n/app_bn.arb**: Add translations for `raidingEventTimeRemaining`, `raidingEventRaided`, `raidingEventJoin`, `raidingEventCanceled`, `subscriptionEvent`, `subscriptionGiftEvent`, `subscriptionMessageEvent`, `realtimeCashDonationWithDonor`, `realtimeCashDonationAnonymous`, `streamElementsTipEventMessage`, and `streamlabsDonationEventMessage`.
* **lib/l10n/app_de.arb**: Add translations for `raidingEventTimeRemaining`, `raidingEventRaided`, `raidingEventJoin`, `raidingEventCanceled`, `subscriptionEvent`, `subscriptionGiftEvent`, `subscriptionMessageEvent`, `realtimeCashDonationWithDonor`, `realtimeCashDonationAnonymous`, `streamElementsTipEventMessage`, and `streamlabsDonationEventMessage`.
* …
=> feat: add translations for raiding and subscription events

lib/components/image/placeholder_image.dart, lib/components/image/resilient_network_image.dart, lib/models/adapters/actions.dart, lib/models/tts.dart, pubspec.lock, pubspec.yaml
Cleans up unused dependencies and simplifies some code.
=> chore: remove unnecessary dependencies

lib/models/adapters/chat_state.dart
Add retry logic to the `getTwitchBadges` method in `lib/models/adapters/chat_state.dart` to handle the `firebase_functions/unavailable` error.
* Use a loop to attempt the Firebase function call up to three times.
* Add a one second delay between each retry attempt.
* Catch the `firebase_functions/unavailable` error and retry if the attempt count is less than three.
* Return an empty list if all attempts fail.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/muxable/rtchat?shareId=99fff9a3-f4b8-4546-90d2-efd7d2b9dc06).
=> feat: retry future up to three times with a one second delay

.github/workflows/codeql-analysis.yml, .github/workflows/firebase-functions-pull-request.yml, .github/workflows/firebase-functions.yml, .github/workflows/firebase-hosting-pull-request.yml, .github/workflows/firebase-hosting.yml, .github/workflows/firebase.yml, .github/workflows/flutter-analyze.yml, .github/workflows/flutter-test.yml
This updates the actions to something more stable while using node 16 instead of 12
=> fix: actions update

lib/components/autocomplete.dart
Not sure if this would help or if you have any suggestions on improving this
=> fix: image quality

lib/models/messages/twitch/channel_point_redemption_event.dart
https://dart.dev/diagnostics/unreachable_switch_default
=> fix: default unreachable in switch

lib/components/disco.dart, lib/components/pinnable/reverse_refresh_indicator.dart, lib/components/stream_preview.dart, lib/screens/settings/tts.dart
https://docs.flutter.dev/release/breaking-changes/wide-gamut-framework
=> fix: opacity migration

lib/urls.dart, pubspec.lock, pubspec.yaml
https://pub.dev/packages/flutter_custom_tabs/changelog to the latest version and opens possibility to use some of the new android features
=> fix: url package

android/app/src/main/kotlin/com/rtirl/chat/AudioService.kt, lib/components/chat_history/message.dart, lib/l10n/app_en.arb, lib/models/tts.dart, lib/screens/home.dart, lib/screens/settings/tts.dart
=> fix: alerts only tts

lib/models/tts.dart, lib/screens/home.dart, lib/screens/settings/tts.dart, lib/tts_isolate.dart
I used claude, not perfect but getting off work machine.
=> fix: tts switch to pass review

lib/models/tts.dart, lib/screens/settings/tts.dart
=> feat: sub only tts

lib/components/autocomplete.dart
Makes the commands appear in landscape without the long description kind of like emotes
=> fix: landscape commands

android/app/src/main/AndroidManifest.xml
@kevmo314 as mentioned for play store
=> fix: android perm tts

android/app/src/main/AndroidManifest.xml
7600edf didn't change the manifest this does to match the new package
=> fix: manifest auth
