lib/components/channel_panel.dart

This makes the chat settings icon visible when using light mode.

Use theme color for chat settings button

---

agent/src/index.ts
agent/tsconfig.json

This uses the service account to retrieve the project id and set it to the different pub/sub resources the agent uses.
I guess something similar could be done to some strings in the functions directory.
Note: I think using .env could be an alternative... but would require setting up `service_account.json` plus `.env` so maybe just using the json file is easier.
Also, can I remove the `build` script in `package.json`? Considering `run` uses ts-node and not the output of build.

Update agent references to the firebase project id

---

lib/models/tts.dart

This prevents TTS from playing the entire chat history queue if the sample is played.

fix: skip to end if forced message is played

---

lib/components/channel_search_dialog.dart

This adds a border decoration to the channel's image when using the channel switcher, the border is colored depending on the channel status.
[Before](https://user-images.githubusercontent.com/994594/125975145-ca84a9cf-fef2-47f4-bc0c-e4e87b8c6325.jpg)
[After - Light](https://user-images.githubusercontent.com/994594/125975148-1191b818-78d6-4ad4-b94c-6666b492521c.jpg)
[After - Dark](https://user-images.githubusercontent.com/994594/125975011-fb278c5b-f829-43b6-85d6-55741faf2b0f.png)

feat: add status indicator to channel switch

---

lib/components/chat_history/stream_state_event.dart

Fixes the stream events widget for light mode.
[Light Mode - before](https://user-images.githubusercontent.com/994594/126020675-e17b4eea-9d3c-48f0-ac58-d953f744a9f2.jpg)
[Light Mode - after](https://user-images.githubusercontent.com/994594/126020646-aaade1a6-45cb-458a-96f8-6383444793dc.jpg)
[Dark Mode](https://user-images.githubusercontent.com/994594/126020700-51cf7f71-7b01-4a76-b887-00fd6f1dc8f7.png)

fix: use theme color for stream events

---

functions/src/subscriptions.ts

Adding the last subscription timestamp so we can prune off channels that nobody is listening to to reduce bandwidth and database writes.

feat: subscription logging

---

lib/models/audio.dart
lib/screens/settings/audio_sources.dart

I don't really know why you would ever _not_ want speaker disconnect protection, perhaps we should keep it always enabled?

feat: always enable speaker disconnect protection

---

lib/components/pinnable/scroll_view.dart

Apparently `dividerColor` is done via alpha transparency instead of being the correct grey color.

fix: use Colors.grey[900] instead of dividerColor

---

lib/components/chat_history/message.dart
lib/components/chat_history/twitch/subscription_event.dart
lib/components/chat_history/twitch/subscription_gift_event.dart
lib/components/chat_history/twitch/subscription_message_event.dart
lib/models/chat_history.dart
lib/models/twitch/subscription_event.dart
lib/models/twitch/subscription_gift_event.dart
lib/models/twitch/subscription_message_event.dart

This adds subscription events to the chat history.
Note: For now, the message sent with resubs is not handled.
[Light Mode](https://user-images.githubusercontent.com/994594/128444867-c98b18ab-087c-4731-a5d7-df3d87459344.jpg)
[Dark Mode](https://user-images.githubusercontent.com/994594/128447108-a18c823f-4cc9-45c6-bd28-05c18d8808db.png)
Side note: Would it make sense to randomize the color of the BorderSide to more easily differentiate each event? (probably from a defined set of colors that work with each theme)

feat: add sub events to chat history

---

lib/components/chat_history/twitch/subscription_message_event.dart

Cumulative Months: The total number of months the user has been subscribed to the channel.

fix: display cumulative months instead of duration for subscriptions

---

functions/src/oauth.ts
lib/components/channel_panel.dart
lib/models/adapters/profiles.dart
lib/models/user.dart

This fixes the case when we no longer have an active refresh token, which may be due to the user changing their account credentials. The token will expire and we delete the profile data to sign the user out.

fix: oauth unlinking error

---

lib/screens/settings/events.dart

Removes the hype train settings items from the page.
I did not remove poll configuration as it is coming with #217.

chore: remove hype train settings

---

lib/models/messages/twitch/event.dart

These fields are stored as [Strings](https://console.firebase.google.com/u/1/project/rtchat-47692/firestore/data/~2Fmessages~2Ftwitch:0mI1Rx5HgDL1gVGQhHRAlNYc9HSKNzIKMpPnWSNXddo%3D): ends_at: "2021-08-15T04:48:09.246733245Z"

fix: parse poll event timestamps

---

functions/src/auth.ts

Fixes #317 
This is if we want to allow signup without email.

fix: allow auth for account with no email

---

lib/screens/settings/activity_feed.dart

The app crashes whenever you open the activity feed while not signed in.

fix: do not render activity feed preview if disabled

---

lib/components/drawer/sidebar.dart

fix: hide refresh audio sources button when there are no audio sources

---

lib/screens/settings/settings.dart

This is probably personal opinion but the current size "feels" off.
Current:
Proposed:

feat: better fit screen orientation toggle

---

lib/main.dart

Only set a global font family instead of a complete theme.
There are a couple elements that are not using the theme so the font is not applied but I guess that can be resolved as part of the individual tasks we have for the new style (onboarding button and search box)

fix: set global font family

---

lib/screens/settings/activity_feed.dart

Currently, if you disable the activity feed while its open on the main page it is not hidden, so the only way to hide it is to use the stream preview button.

fix: hide activity feed on disable

---

lib/models/tts.dart

Closes #358
This works by tracking the timestamp of the latest message and rejecting messages in the past.

fix: track tts most recent message timestamp

---

lib/screens/home.dart

Adds a tooltip to the tts icon to make it consistent with the other icons in the appbar

fix: add tts icon tooltip

---

lib/screens/home.dart

When resizing the activity feed, if you drag past the size bounds, you have to drag the same distance you over-dragged before it starts resizing in the other direction. Clamping the height/width values on drag end fixes this.

fix: clamp resize overscroll

---

lib/components/chat_panel.dart

This bug occurs when a user when a user doesn't have enough messages to scroll. Follow these steps to reproduce:
1. Resize the activity panel to cover the top message
2. Scroll up
3. Resize the activity panel to show all messages
The scroll to bottom button persists and cannot be dismissed by tapping while it is at the bottom of the scroll.
Calling `updateScrollPosition()` when the button is pressed dismisses the button in this case.

fix: fix button at bottom of scroll

---

agent/src/agents/twitch.ts

Adds twitch prefix to message id for #305

fix: incorrect message id reference in reply

---

lib/models/messages/twitch/message_configuration.dart

For very large channels, the behavior is a bit confusing because apparently VIPs and mods send a lot of messages

fix: default vips and mods to unpinned

---

lib/screens/onboarding.dart

"Continue without Signing In" is a bit long and wraps on some screens.

fix: shorten button text

---

lib/components/chat_history/twitch/badge.dart

`Uri.tryParse()` throws an exception when passed a null value.

fix: handle null badge url

---

lib/components/chat_history/twitch/prediction_event.dart

Improves the legibility of prediction events in dark mode
Before:
After:

fix: improve prediction event legibility

---

lib/screens/settings/twitch/badges.dart

The unselected badges checkbox has little contrast with the new dark grey appbar in light mode.

fix: improve checkbox visibility in light mode

---

lib/components/drawer/quicklinks_listview.dart

Quick link list order now matches between those two pages. Since we allow
users to reorder the list, it should match in the drawer.

feat: match drawer and settings quicklink order

---

lib/components/drawer/end_drawer.dart

Users at the bottom of the viewer list can be hidden by the phone's navigation bar

fix: add padding to bottom of viewer list

---

.github/workflows/ios.yml

Looks like GitHub Actions uses M1 chipped computers sometimes now.

ci: install rosetta

---

lib/components/chat_panel.dart
lib/models/adapters/messages.dart

closes #497 
Firestore is queried to confirm that a channel is quiet instead of the messages not yet being loaded.

feat: indicate if there are no messages

---

lib/screens/home.dart

closes #499 
Swiping on the left two thirds of the screen opens the drawer and swiping on the right third opens the viewer list.

feat: swipe to open drawers

---

lib/components/drawer/end_drawer.dart
lib/components/drawer/sliver_search_bar.dart

I incorrectly diagnosed what was causing the issue I attempted to fix in #512. The issue was caused by `SliverPadding` widgets without a sliver child. When scrolling to the bottom, they would collect at the top of the screen preventing the user from being able to scroll to the bottom of the list. Adding the `SliverTitleWidget` widget to the `SliverPadding` fixes this. I also adjusted the padding to better match the mock.

fix: fix viewer list padding

---

lib/components/chat_history/message.dart

adding the `primary: false` flag causes to the long press menu to only show the overscroll effect if necessary

style: disable long press menu overscroll effect

---

lib/models/audio.dart

I was watching YouTube on my Android phone when the volume lowered. I realized I had rtchat open and it was caused by the periodic silent sound ducking the audio. The strange thing is that it didn't return to full volume after playing. Only after I closed rtchat did it return to full volume.

fix: only duck audio on iOS

---

lib/components/chat_history/message.dart

I believe this is a bit more clear, otherwise you could believe the app will copy the link to the clipboard?

chore: reword link to user profile

---

lib/models/tts.dart

In some languages (eg German), the dashes aren't read correctly. We should localize, but until then this is a decent solution.

fix: remove dashes

---

lib/components/stream_preview.dart

In light mode, the stream preview buttons are black, blending in to the dark background

feat: improve stream preview icons visibility

---

lib/components/stream_preview.dart

Currently the stream preview buttons can be pressed when they aren't visible

fix: disable buttons when overlay is inactive

---

lib/components/emote_picker.dart
lib/themes.dart

Not completely sure these are the best but it's visible on light mode

fix: update emote picker colors for light mode

---

agent/src/agents/twitch.ts

This fixes the duplicate message bug if multiple agents are listening

fix: claim messages before sending

---

lib/models/messages/twitch/event.dart

https://dev.twitch.tv/docs/eventsub/eventsub-reference/#choices
Looks like bits can not be used for polls? I didn't remove it yet just in case.

fix: update field name of bit and channel point poll vote count

---

firebase.json
functions/src/index.ts
lib/components/stream_preview.dart
lib/screens/home.dart

fix: use redirect for embedded twitch viewer

---

functions/src/eventsub.ts

We ignored invalid signatures for a long time because I accidentally changed the secret key. It's been long enough so we should prune off these subscriptions.

fix: start rejecting invalid signatures

---

functions/src/eventsub.ts

Reverts muxable/rtchat#777
Maybe twitch doesn't delete invalid eventsubs as quickly as I had hoped.

Revert "fix: start rejecting invalid signatures (#777)"

---

lib/components/channel_search_results.dart

The problem is more relevant on light mode.

fix: update search image stack to not clip promoted icon

---

lib/screens/settings/quick_links.dart

This makes both things work but I feel like it could be better to just add a '?' icon on the top right explaining the gestures instead of the tooltip?

fix: use tap for quicklink tooltip since longpress conflicts with reorderlistview

---

functions/src/chat-status.ts

```
Unhandled error TypeError: Cannot read properties of undefined (reading 'length')
at undefined. ( [/workspace/lib/chat-status.js:143](https://console.cloud.google.com/debug?referrer=fromlog&file=%2Fworkspace%2Flib%2Fchat-status.js&line=143&project=rtchat-47692) )
at .processTicksAndRejections ( [node:internal/process/task_queues:96](https://console.cloud.google.com/debug?referrer=fromlog&file=node:internal%2Fprocess%2Ftask_queues&line=96&project=rtchat-47692) )
```

fix: getViewerList exception

---

functions/src/chat-status.ts

Looks like we're passing twitch id instead of login.

fix: use login instead of twitch id to get viewer list

---

android/app/src/main/kotlin/com/rtirl/chat/AudioService.kt

A RuntimException is thrown otherwise.

fix: only release wakelock if held

---

functions/src/eventsub.ts

https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelshoutoutcreate
https://discuss.dev.twitch.tv/t/new-shoutouts-api-and-eventsub-subscription-types-are-now-in-open-beta/42906

feat: include shoutout eventsub that is currently in beta

---

lib/screens/settings/twitch/badges.dart

The current bar takes up too much space.
before:
after:

fix: expanded height size

---

lib/screens/settings/chat_history.dart

Might help people find the setting.
before:
after:

fix: badge settings visibility

---

lib/components/channel_search_results.dart

This rolls back the rendering part of #923

fix: render only the display name

---

lib/models/tts.dart

These apis seem to change between iOS versions which is why I excluded some of the common options, tested on 16.0

feat: allow tts to play in the background on ios

---

functions/src/search.ts

We were accessing the response as if it was exactly as a `/streams/followed` call.
Example response:
```bash
$ twitch api get search/channels -q query=muxfd
{
"data": [
{
"broadcaster_language": "en",
"broadcaster_login": "murfdawgg",
"display_name": "Murfdawgg",
"game_id": "0",
"game_name": "",
"id": "20060690",
"is_live": false,
"started_at": "",
"tag_ids": [],
"tags": [],
"thumbnail_url": "https://static-cdn.jtvnw.net/jtv_user_pictures/murfdawgg-profile_image-bd7db3e49d25d042-300x300.png",
"title": ""
},
{
"broadcaster_language": "",
"broadcaster_login": "muxfede10",
"display_name": "muxfede10",
"game_id": "0",
"game_name": "cs go",
"id": "29855675",
"is_live": false,
"started_at": "",
"tag_ids": [],
"tags": [],
"thumbnail_url": …
```

fix: properly access fields from search/channels response

---

lib/components/chat_history/twitch/raid_event.dart

Closes #918
its already implemented but ig we can trigger the eventsub with the text `/shoutout <streamer>`

chore: replaced textlink shoutout with eventsub shoutout in inbound raid

---

lib/components/chat_history/twitch/subscription_event.dart

This moves away from #D2D2E6 a gray to #9A93A9 more of a purple which provides more visibility against the white text.

fix: tier 2 color contrast

---

lib/components/stream_preview.dart

https://console.firebase.google.com/u/0/project/rtchat-47692/crashlytics/app/android:com.rtirl.chat/issues/fbe29b8c363b11272522f3dac523469d?time=last-seven-days&sessionEventKey=64299AED00D30001749E953E28A7C2EB_1795948315917602999

fix: stream preview model used over async gap

---

lib/screens/settings/activity_feed.dart

https://console.firebase.google.com/u/0/project/rtchat-47692/crashlytics/app/android:com.rtirl.chat/issues/a08b2039abed6de296ccabd0ab123f02?time=last-seven-days&versions=2.3.11%20(6953148)&sessionEventKey=64293F3F00AE00011CD8011F56221655_1795815388620009013

fix: remove incorrect late final from activity feed

---

functions/src/emotes.ts

The global 7tv emotes appear to be broken because the api has been deprecated.

fix: broken 7tv emotes

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/kotlin/com/rtirl/chat/MainActivity.kt
lib/components/message_input.dart
lib/screens/settings/qr.dart
lib/share_channel.dart

- receive sharing intents from other apps and populate the text field automatically.

feat: receive sharing intents android

---

ios/Runner/Info.plist

This has been fixed into the flutter engine and also avoids warnings in Xcode
https://developer.apple.com/documentation/uikit/uiapplication/1623026-statusbarorientation?language=objc

fix: remove deprecation

---

android/app/src/main/kotlin/com/rtirl/chat/MainActivity.kt
lib/components/drawer/sidebar.dart
lib/main.dart
lib/models/tts.dart
lib/screens/home.dart
lib/screens/settings/audio_sources.dart
lib/tts_isolate.dart
lib/tts_plugin.dart
pubspec.lock
pubspec.yaml
test/models/tts_test.dart

This disabled tts if the queue gets too long.

fix: disable if tts gets too long

---

lib/screens/home.dart

- I moved the function to listen to TTS above this line ` if (model.sources.isEmpty || (await AudioChannel.hasPermission())) {
return;
}` because the function may not always be reached .

fix: removing listener from mounted check

---

android/app/src/main/kotlin/com/rtirl/chat/MainActivity.kt
lib/main.dart
lib/models/tts.dart
lib/tts_isolate.dart
lib/tts_plugin.dart

fix: update get vocalization in the isolate

---

.github/workflows/firebase-functions-pull-request.yml

This commit removed it just for the main branch https://github.com/muxable/rtchat/commit/6d44dce62d5bc3c91a23b618025b1c87fe3e18a4 so now on this run https://github.com/muxable/rtchat/actions/runs/8989985585/job/24694274860 it tells me the minimum supported version is 18

fix: upgrade node version

---

lib/components/chat_history/twitch/subscription_event.dart

The wording on https://github.com/muxable/rtchat/commit/5bb09db9c2e31846add426963fffef813f60c30f with the change of where the position is slightly off

fix: sub event wording

---

lib/components/auth/twitch.dart
lib/screens/settings/tts.dart
lib/themes.dart
pubspec.lock
pubspec.yaml

This PR does the following
- Upgrades intl to 0.19.0 as required by flutter 3.22
- Changes from MaterialState to WidgetState as introduced in 3.22 https://api.flutter.dev/flutter/material/MaterialState.html
- Changes background to surface https://api.flutter.dev/flutter/material/ColorScheme/background.html

fix: flutter 3.22 deprecations

---

lib/tts_isolate.dart

Related to #1252
Implements bot message muting in the TTS engine within `lib/tts_isolate.dart` as per the issue requirements.
- Adds a check to determine if a message originates from a bot using the `isBotMuted` flag and the author's bot status before vocalization.
- Skips the vocalization process for messages identified as originating from bots, effectively muting them.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/muxable/rtchat/issues/1252?shareId=1deebb38-fb77-44bf-8432-4a0ac30b246d).

fix: support muting bots in new TTS engine

---

lib/l10n/app_en.arb
lib/screens/settings/events.dart

Localizes hardcoded strings in `lib/screens/settings/events.dart` and updates `lib/l10n/app_en.arb` with new entries for localization.
- Replaces hardcoded strings in `lib/screens/settings/events.dart` with references to `AppLocalizations` to support localization.
- Adds new entries for all the replaced strings in `lib/l10n/app_en.arb`, including titles and subtitles for event configurations like follow, subscribe, cheer, raid, host, hypetrain, poll, prediction, channel point redemption, and outgoing raid events.
- Ensures that the localization keys and their values in `app_en.arb` match the references added in the Dart code, facilitating future translations and maintaining consistency across the application.
---
For more details, open the [Copilot Workspace …

feat: localize hardcoded strings in settings events screen

---

lib/components/chat_history/twitch/raid_event.dart
lib/components/chat_history/twitch/raiding_event.dart

Replaces `Text.rich` widgets with `StyledText` widgets in `raid_event.dart` and `raiding_event.dart` files to improve text formatting consistency.
- **Text Formatting**: Implements `StyledText` for dynamic text formatting in `raid_event.dart` and `raiding_event.dart`, replacing the previous `Text.rich` implementations. This change aligns with the use of `StyledText` in other parts of the application for consistent text styling.
- **Tag-based Styling**: Utilizes tags within `StyledText` to apply text styles, making the code more readable and maintainable. This approach simplifies the styling process by using predefined tags instead of manual `TextSpan` configurations.
- **Maintains Visual Output**: Ensures that the visual output remains unchanged by matching the `StyledText` styling with …

refactor: replace rich text spans with StyledText

---

lib/components/chat_history/twitch/subscription_event.dart

Replaces `Text.rich` with `StyledText` in `subscription_event.dart` for enhanced text styling and consistency with `follow_event.dart`.
- Imports the `styled_text` package at the beginning of the file to enable the use of `StyledText`.
- Updates `TwitchSubscriptionEventWidget`, `TwitchSubscriptionGiftEventWidget`, and `TwitchSubscriptionMessageEventWidget` to use `StyledText` instead of `Text.rich`. This change allows for more flexible and consistent text styling across different event types.
- Utilizes `StyledTextTag` within `StyledText` to maintain existing text styles and apply additional styling where necessary, ensuring visual consistency with the rest of the application.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/muxable/rtchat …

refactor: replace Text.rich with StyledText in subscription events

---

lib/components/chat_history/twitch/hype_train_event.dart

Updates the text rendering in `TwitchHypeTrainEventWidget` to use `StyledText()` for a more flexible and maintainable approach to styling.
- Replaces `Text.rich()` with `StyledText()` for rendering text, aligning with the proposed resolution to utilize `StyledText()` for text styling.
- Utilizes tags within `StyledText()` to apply styles, specifically using the `<b>` tag to style certain text segments as bold, which is achieved through the `StyledTextTag` and leveraging the `Theme.of(context).textTheme.titleSmall` for styling.
- Maintains the original text content and structure, ensuring that the transition to `StyledText()` does not alter the message conveyed to the user.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/muxable/rtchat?sha …

refactor: convert hype train event to StyledText

---

lib/components/chat_history/twitch/cheer_event.dart

Updates the text formatting in `lib/components/chat_history/twitch/cheer_event.dart` to use `StyledText` instead of `Text.rich`.
- Replaces `Text.rich` with `StyledText` for rendering the cheer event message, enhancing the text formatting capabilities.
- Introduces `StyledTextTag` to apply a bold style to specific parts of the text, matching the original styling intent while utilizing the new `StyledText` functionality.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/muxable/rtchat?shareId=cc121534-eacb-4c5c-a3a7-72a79cbe5958).

refactor: convert CheerEvent to use StyledText

---

lib/components/chat_history/twitch/channel_point_event.dart
test/components/chat_history/twitch/channel_point_event_test.dart

Upgrades the TwitchChannelPointRedemptionEventWidget to use `StyledText` for enhanced text styling.
- Replaces `Text.rich` with `StyledText` widget to allow for more complex text styling and formatting.
- Utilizes `StyledText` tags to apply text styles, specifically using the `<b>` tag to bold the redeemer's username and the reward name.
- Preserves the existing text styles by mapping them to the `StyledTextTag` with the style defined in the theme's `titleSmall`.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/muxable/rtchat?shareId=e5a42171-15f2-496f-a8bb-38079fae1ecc).

refactor: convert channel point events to StyledText

---

lib/components/chat_history/auxiliary/realtimecash_donation.dart
lib/components/chat_history/auxiliary/streamelements.dart
lib/components/chat_history/auxiliary/streamlabs.dart
lib/components/chat_history/twitch/channel_point_event.dart
lib/components/chat_history/twitch/cheer_event.dart
lib/components/chat_history/twitch/host_event.dart
lib/components/chat_history/twitch/hype_train_event.dart
lib/components/chat_history/twitch/raiding_event.dart
lib/l10n/app_en.arb
test/components/chat_history/twitch/channel_point_event_test.dart
test/components/chat_history/twitch/host_event_test.dart
test/components/l10n.dart

Localizes static strings in various components of the chat history, including those with style tags, and updates localization files.
- Localizes static strings in `RealtimeCashDonationEventWidget`, `StreamElementsTipEventWidget`, `StreamlabsDonationEventWidget`, `TwitchChannelPointRedemptionEventWidget`, `TwitchCheerEventWidget`, `TwitchHostEventWidget`, and `TwitchHypeTrainEventWidget`. This includes handling both cases where the donor is known and anonymous, as well as including style tags within the localized strings as needed.
- Updates the `app_en.arb` localization file with new entries for the localized strings extracted from the above components. This ensures that all static strings, including those with style tags, are now localized according to the task requirements.
- Ensures …

feat: localize static strings in chat history components

---

ios/Podfile.lock
pubspec.lock
pubspec.yaml

This updates the in app purchases package to support a minimum of iOS 12, url launcher to include privacy manifests, path provider includes privacy manifests

chore: upgrade packages

---

ios/Podfile.lock
lib/screens/home.dart
pubspec.lock
pubspec.yaml

This upgrades the wakelock to the new version and the package info plus as well to work with the latest version of flutter. To test the wakelock working it will only work on an actual device and not a simulator.

fix: swap wakelock and dependencies

---

lib/components/emote_picker.dart

When migrating from material 2 to material 3 it changed the way the emote picker worked, this led to emotes being present behind the channel text and not matching the native app. I added the bar again and kept most material 3 improvements.

fix: emote picker migration

---

lib/l10n/app_bn.arb
lib/l10n/app_de.arb
lib/l10n/app_es.arb
lib/l10n/app_fr.arb
lib/l10n/app_ja.arb
lib/l10n/app_nl.arb
lib/l10n/app_pt.arb
lib/l10n/app_zh.arb
lib/l10n/app_zh_Hant.arb

Add translations for various event-related strings in multiple languages.
* **Add translations in `lib/l10n/app_bn.arb`**:
- Add translations for `errorFetchingViewerList`, `eventsTitle`, `followEventConfigTitle`, `customizeYourFollowEvent`, `subscribeEventConfigTitle`, `customizeYourSubscriptionEvent`, `cheerEventConfigTitle`, `customizeYourCheerEvent`, `raidEventConfigTitle`, `customizeYourRaidEvent`, `hostEventConfigTitle`, `customizeYourHostEvent`, `hypetrainEventConfigTitle`, and `customizeYourHypetrainEvent`.
* **Add translations in `lib/l10n/app_de.arb`**:
- Add translations for `errorFetchingViewerList`, `eventsTitle`, `followEventConfigTitle`, `customizeYourFollowEvent`, `subscribeEventConfigTitle`, `customizeYourSubscriptionEvent`, `cheerEventConfigTitle`, …

feat: add translations for new keys

---

lib/l10n/app_bn.arb
lib/l10n/app_de.arb
lib/l10n/app_es.arb
lib/l10n/app_fr.arb
lib/l10n/app_ja.arb
lib/l10n/app_nl.arb
lib/l10n/app_pt.arb
lib/l10n/app_zh.arb
lib/l10n/app_zh_Hant.arb

Add translations for various event messages in multiple language files.
* **Bengali (app_bn.arb)**
- Add translations for `channelPointRedemptionWithUserInput`, `channelPointRedemptionWithoutUserInput`, `cheerEventMessage`, `anonymous`, `hostEventMessage`, `hypeTrainEventProgress`, `hypeTrainEventEndedSuccessful`, and `hypeTrainEventEndedUnsuccessful`.
* **German (app_de.arb)**
- Add translations for `channelPointRedemptionWithUserInput`, `channelPointRedemptionWithoutUserInput`, `cheerEventMessage`, `anonymous`, `hostEventMessage`, `hypeTrainEventProgress`, `hypeTrainEventEndedSuccessful`, and `hypeTrainEventEndedUnsuccessful`.
* **Spanish (app_es.arb)**
- Add translations for `channelPointRedemptionWithUserInput`, `channelPointRedemptionWithoutUserInput`, `cheerEventMessage`, …

Add translations for various event messages

---

lib/l10n/app_en.arb
lib/l10n/app_pt.arb
lib/l10n/app_zh_Hant.arb

This translation string is a dupe, otherwise since it appears in two different screen I can rename it to make it easily distinguishable.

fix: dupe translation string

---

lib/components/channel_search_bottom_sheet.dart

Fixes stack trace:
```
Fatal Exception: FlutterError
0  ???                            0x0 _ChannelSearchBottomSheetWidgetState.build.<fn> + 96 (channel_search_bottom_sheet.dart:96)
1  ???                            0x0 _ChannelSearchResultsWidgetState.build.<fn>.<fn>.<fn> + 226 (channel_search_results.dart:226)
2  ???                            0x0 _InkResponseState.handleTap + 1171 (ink_well.dart:1171)
3  ???                            0x0 GestureRecognizer.invokeCallback + 344 (recognizer.dart:344)
4  ???                            0x0 TapGestureRecognizer.handleTapUp + 652 (tap.dart:652)
5  ???                            0x0 BaseTapGestureRecognizer._checkUp + 309 (tap.dart:309)
6  ???                            0x0 BaseTapGestureRecognizer.acceptGesture + 279 (tap.dart:279)
7  ??? …
```

fix: raid null check

---

lib/components/emote_picker.dart

Replace the usage of the deprecated 'onPopInvoked' with 'onPopInvokedWithResult' in `lib/components/emote_picker.dart`.
* Update the callback function to match the new signature of 'onPopInvokedWithResult'.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/muxable/rtchat?shareId=4a472c99-6d24-46d4-82bd-aca5359335d5).

fix: fix deprecation warning in emote_picker.dart

---

ios/Runner/AppDelegate.swift

```ios/Runner/AppDelegate.swift uses the deprecated @UIApplicationMain attribute, updating.```
https://forums.swift.org/t/se-0383-deprecate-uiapplicationmain-and-nsapplicationmain/62375
https://github.com/flutter/flutter/issues/143044

fix: migrate @UIApplicationMain attribute to @main

---

lib/components/auth/companion_auth.dart

Fix the analyzer warning about using 'BuildContext' across async gaps in `lib/components/auth/companion_auth.dart`.
* Move the `Provider.of<UserModel>(context, listen: false)` call to before the async gap.
* Store the `UserModel` instance in a local variable.
* Move the `Navigator.of(context)` call to before the async gap and store it in a local variable.
* Use the local variables instead of calling `Provider.of<UserModel>(context, listen: false)` and `Navigator.of(context)` after the async gap.
* Retain the `mounted` check before calling `navigator.pop()`.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/muxable/rtchat?shareId=ff920a9b-a15c-4ad8-9afd-9ae02d81b5b3).

fix: analyzer warning in companion_auth.dart

---

lib/screens/settings/audio_sources.dart

Update `add` method in `lib/screens/settings/audio_sources.dart` to handle metadata lookup failures.
* **Metadata Fetching:**
- Wrap `MetadataFetch.extract` call with a try/catch block to handle potential exceptions.
- Assign `null` to `metadata` if an exception occurs.
- Use the URL hostname as the title if metadata lookup fails.
* **Audio Source Addition:**
- Update the `addSource` method to use the title derived from metadata or URL hostname.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/muxable/rtchat?shareId=ca02a26f-092f-431a-8af6-fe22ca8bdcc6).

fix: metadata lookup failure handling

---

lib/models/adapters/chat_state.dart

Update `getTwitchBadges` function to retry up to 10 times with exponential back off.
* Modify the `getTwitchBadges` function in `lib/models/adapters/chat_state.dart` to retry up to 10 times.
* Implement exponential back off with a base delay of 1 second.
* Increase the delay exponentially with each retry.
* Handle the "UNAVAILABLE" error gracefully beyond the 10 attempts.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/muxable/rtchat?shareId=6000ec19-679d-44b5-ad87-8cbf85764fde).

fix: update retry logic in getTwitchBadges function

---

android/gradle/wrapper/gradle-wrapper.properties
android/settings.gradle

Upgraded one version to fix the build failing or I could do maybe the workaround fix mentioned on https://issuetracker.google.com/issues/242308990
```┌─ Flutter Fix ────────────────────────────────────────────────────────────────────────────────────┐
│ [!] Version 7.3 of the Android Gradle Plugin (AGP) uses a version of R8 that contains a bug      │
│ which causes this error (see more info at https://issuetracker.google.com/issues/242308990).     │
│ To fix this error, update to a newer version of AGP (at least 7.4.0).                            │
│                                                                                                  │
│  The version of AGP that your project uses is likely defined in:                                 │
│ …
```

fix: gradle causing builds to fail

---

lib/components/message_input.dart
lib/components/pinnable/reverse_refresh_indicator.dart

Make `_textEditingController` nullable and non-final in `message_input.dart` and handle all the null check cases.
* Change `_textEditingController` to nullable by updating its type to `EmoteTextEditingController?`.
* Add null checks before accessing `_textEditingController` in `didUpdateWidget`, `_handleSharedData`, `dispose`, and `sendMessage` methods.
* Update the `TextField` widget in the `build` method to handle the case when `_textEditingController` is null.
* Use null-aware operators to safely access `_textEditingController` properties and methods.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/muxable/rtchat/pull/1331?shareId=b978c8c3-fec7-4ac3-91d4-f644eb539b9b).

fix: make _textEditingController nullable and non-final in message_input.dart
